from backend.rbac.permissions import (
    OrgPermission,
    TeamPermission,
    ORG_ROLE_PERMISSIONS,
    TEAM_ROLE_PERMISSIONS,
    has_org_permission,
    has_team_permission,
    can_assign_org_role,
    can_assign_team_role,
)
from backend.rbac.deps import (
    OrganizationContext,
    TeamContext,
    OrgContextDep,
    TeamContextDep,
    PlatformAdminDep,
    RequireOrgOwnerDep,
    RequireOrgAdminDep,
    RequireTeamAdminDep,
    get_organization,
    get_organization_by_slug,
    get_org_membership,
    get_org_context,
    get_team,
    get_team_by_slug,
    get_team_membership,
    get_team_context,
    require_org_permission,
    require_team_permission,
    require_org_owner,
    require_org_admin,
    require_team_admin,
    get_current_platform_admin,
)

__all__ = [
    # Permission enums
    "OrgPermission",
    "TeamPermission",
    # Permission mappings
    "ORG_ROLE_PERMISSIONS",
    "TEAM_ROLE_PERMISSIONS",
    # Permission check functions
    "has_org_permission",
    "has_team_permission",
    "can_assign_org_role",
    "can_assign_team_role",
    # Context classes
    "OrganizationContext",
    "TeamContext",
    # Type aliases for dependency injection
    "OrgContextDep",
    "TeamContextDep",
    "PlatformAdminDep",
    "RequireOrgOwnerDep",
    "RequireOrgAdminDep",
    "RequireTeamAdminDep",
    # Dependency functions
    "get_organization",
    "get_organization_by_slug",
    "get_org_membership",
    "get_org_context",
    "get_team",
    "get_team_by_slug",
    "get_team_membership",
    "get_team_context",
    "require_org_permission",
    "require_team_permission",
    "require_org_owner",
    "require_org_admin",
    "require_team_admin",
    "get_current_platform_admin",
]
