"""add rag settings tables

Revision ID: 1453168337f4
Revises: 270386205709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1453168337f4'
down_revision: Union[str, Sequence[str], None] = '270386205709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_rag_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rag_enabled', sa.Boolean(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('chunks_per_query', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('use_hybrid_search', sa.Boolean(), nullable=False),
    sa.Column('reranking_enabled', sa.Boolean(), nullable=False),
    sa.Column('query_rewriting_enabled', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('rag_customization_enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_team_customization', sa.Boolean(), nullable=False),
    sa.Column('allow_user_customization', sa.Boolean(), nullable=False),
    sa.Column('max_documents_per_user', sa.Integer(), nullable=False),
    sa.Column('max_document_size_mb', sa.Integer(), nullable=False),
    sa.Column('max_total_storage_gb', sa.Integer(), nullable=False),
    sa.Column('allowed_file_types', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('user_rag_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('rag_enabled', sa.Boolean(), nullable=False),
    sa.Column('chunks_per_query', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('team_rag_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rag_enabled', sa.Boolean(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('chunks_per_query', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('use_hybrid_search', sa.Boolean(), nullable=False),
    sa.Column('reranking_enabled', sa.Boolean(), nullable=False),
    sa.Column('query_rewriting_enabled', sa.Boolean(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('rag_customization_enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_user_customization', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    # NOTE: Do not drop LangGraph checkpoint tables (managed by LangGraph, not SQLModel)
    # These tables are: checkpoints, checkpoint_blobs, checkpoint_writes, checkpoint_migrations
    # And: store, store_vectors, store_migrations, vector_migrations
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop RAG settings tables only
    op.drop_table('team_rag_settings')
    op.drop_table('user_rag_settings')
    op.drop_table('organization_rag_settings')
    # ### end Alembic commands ###
