"""add theme settings tables

Revision ID: 270386205709
Revises: 959c0f0c6e08

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '270386205709'
down_revision: Union[str, Sequence[str], None] = '959c0f0c6e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create enum types first
    sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitationstatus').create(op.get_bind(), checkfirst=True)
    sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='orgrole').create(op.get_bind(), checkfirst=True)
    sa.Enum('ADMIN', 'MEMBER', 'VIEWER', name='teamrole').create(op.get_bind(), checkfirst=True)

    op.create_table('organization_theme_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('default_theme_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_light_theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_dark_theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_light_theme', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_dark_theme', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('theme_customization_enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_team_customization', sa.Boolean(), nullable=False),
    sa.Column('allow_user_customization', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('user_theme_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('theme_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('light_theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dark_theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_light_theme', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_dark_theme', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('team_theme_settings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('default_theme_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_light_theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_dark_theme', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_light_theme', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_dark_theme', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('theme_customization_enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_user_customization', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.drop_index(op.f('checkpoint_blobs_thread_id_idx'), table_name='checkpoint_blobs')
    op.drop_table('checkpoint_blobs')
    op.drop_index(op.f('checkpoint_writes_thread_id_idx'), table_name='checkpoint_writes')
    op.drop_table('checkpoint_writes')
    op.drop_index(op.f('store_vectors_embedding_idx'), table_name='store_vectors', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('store_vectors')
    op.drop_table('vector_migrations')
    op.drop_index(op.f('idx_store_expires_at'), table_name='store', postgresql_where='(expires_at IS NOT NULL)')
    op.drop_index(op.f('store_prefix_idx'), table_name='store', postgresql_ops={'prefix': 'text_pattern_ops'})
    op.drop_table('store')
    op.drop_table('checkpoint_migrations')
    op.drop_table('store_migrations')
    op.drop_index(op.f('checkpoints_thread_id_idx'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_prompt_is_active'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_org_scope'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_organization_id'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_team_id'), table_name='prompt')
    op.drop_index(op.f('ix_prompt_user_id'), table_name='prompt')
    op.drop_table('prompt')
    op.drop_index(op.f('idx_conversation_message_content_gin'), table_name='conversation_message', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_conversation_message_team_user'), table_name='conversation_message')
    op.execute("ALTER TABLE invitation ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE invitation ALTER COLUMN status TYPE invitationstatus USING status::text::invitationstatus")
    op.execute("ALTER TABLE invitation ALTER COLUMN status SET DEFAULT 'PENDING'::invitationstatus")
    op.alter_column('mcp_server', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('mcp_server', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mcp_server', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_mcp_server_org'), table_name='mcp_server')
    op.drop_index(op.f('idx_mcp_server_team'), table_name='mcp_server', postgresql_where='(team_id IS NOT NULL)')
    op.drop_index(op.f('idx_mcp_server_user'), table_name='mcp_server', postgresql_where='(user_id IS NOT NULL)')
    op.drop_constraint(op.f('mcp_server_created_by_id_fkey'), 'mcp_server', type_='foreignkey')
    op.create_foreign_key(None, 'mcp_server', 'user', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.execute("ALTER TABLE organization_member ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE organization_member ALTER COLUMN role TYPE orgrole USING role::text::orgrole")
    op.execute("ALTER TABLE organization_member ALTER COLUMN role SET DEFAULT 'MEMBER'::orgrole")
    op.drop_constraint(op.f('uq_organization_member_org_user'), 'organization_member', type_='unique')
    op.drop_constraint(op.f('uq_team_org_slug'), 'team', type_='unique')
    op.create_index(op.f('ix_team_organization_id'), 'team', ['organization_id'], unique=False)
    op.execute("ALTER TABLE team_member ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE team_member ALTER COLUMN role TYPE teamrole USING role::text::teamrole")
    op.execute("ALTER TABLE team_member ALTER COLUMN role SET DEFAULT 'MEMBER'::teamrole")
    op.drop_constraint(op.f('uq_team_member_team_org_member'), 'team_member', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_team_member_team_org_member'), 'team_member', ['team_id', 'org_member_id'], postgresql_nulls_not_distinct=False)
    op.execute("ALTER TABLE team_member ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE team_member ALTER COLUMN role TYPE VARCHAR(20) USING role::text")
    op.execute("ALTER TABLE team_member ALTER COLUMN role SET DEFAULT 'member'::character varying")
    op.drop_index(op.f('ix_team_organization_id'), table_name='team')
    op.create_unique_constraint(op.f('uq_team_org_slug'), 'team', ['organization_id', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_organization_member_org_user'), 'organization_member', ['organization_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.execute("ALTER TABLE organization_member ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE organization_member ALTER COLUMN role TYPE VARCHAR(20) USING role::text")
    op.execute("ALTER TABLE organization_member ALTER COLUMN role SET DEFAULT 'member'::character varying")
    op.drop_constraint(None, 'mcp_server', type_='foreignkey')
    op.create_foreign_key(op.f('mcp_server_created_by_id_fkey'), 'mcp_server', 'user', ['created_by_id'], ['id'])
    op.create_index(op.f('idx_mcp_server_user'), 'mcp_server', ['user_id'], unique=False, postgresql_where='(user_id IS NOT NULL)')
    op.create_index(op.f('idx_mcp_server_team'), 'mcp_server', ['team_id'], unique=False, postgresql_where='(team_id IS NOT NULL)')
    op.create_index(op.f('idx_mcp_server_org'), 'mcp_server', ['organization_id'], unique=False)
    op.alter_column('mcp_server', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mcp_server', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('mcp_server', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.execute("ALTER TABLE invitation ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TABLE invitation ALTER COLUMN status TYPE VARCHAR(20) USING status::text")
    op.execute("ALTER TABLE invitation ALTER COLUMN status SET DEFAULT 'pending'::character varying")
    op.create_index(op.f('idx_conversation_message_team_user'), 'conversation_message', ['team_id', 'created_by_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_conversation_message_content_gin'), 'conversation_message', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_table('prompt',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prompt_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('prompt_created_by_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('prompt_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('prompt_team_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('prompt_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('prompt_pkey'))
    )
    op.create_index(op.f('ix_prompt_user_id'), 'prompt', ['user_id'], unique=False)
    op.create_index(op.f('ix_prompt_team_id'), 'prompt', ['team_id'], unique=False)
    op.create_index(op.f('ix_prompt_organization_id'), 'prompt', ['organization_id'], unique=False)
    op.create_index(op.f('ix_prompt_org_scope'), 'prompt', ['organization_id', 'team_id', 'user_id', 'prompt_type'], unique=False)
    op.create_index(op.f('ix_prompt_is_active'), 'prompt', ['is_active'], unique=False)
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('checkpoint', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', name=op.f('checkpoints_pkey'))
    )
    op.create_index(op.f('checkpoints_thread_id_idx'), 'checkpoints', ['thread_id'], unique=False)
    op.create_table('store_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('store_migrations_pkey'))
    )
    op.create_table('checkpoint_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('checkpoint_migrations_pkey'))
    )
    op.create_table('store',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ttl_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('prefix', 'key', name='store_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('store_prefix_idx'), 'store', ['prefix'], unique=False, postgresql_ops={'prefix': 'text_pattern_ops'})
    op.create_index(op.f('idx_store_expires_at'), 'store', ['expires_at'], unique=False, postgresql_where='(expires_at IS NOT NULL)')
    op.create_table('vector_migrations',
    sa.Column('v', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('v', name=op.f('vector_migrations_pkey'))
    )
    op.create_table('store_vectors',
    sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['prefix', 'key'], ['store.prefix', 'store.key'], name=op.f('store_vectors_prefix_key_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prefix', 'key', 'field_name', name=op.f('store_vectors_pkey'))
    )
    op.create_index(op.f('store_vectors_embedding_idx'), 'store_vectors', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('checkpoint_writes',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idx', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('task_path', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx', name=op.f('checkpoint_writes_pkey'))
    )
    op.create_index(op.f('checkpoint_writes_thread_id_idx'), 'checkpoint_writes', ['thread_id'], unique=False)
    op.create_table('checkpoint_blobs',
    sa.Column('thread_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('blob', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'channel', 'version', name=op.f('checkpoint_blobs_pkey'))
    )
    op.create_index(op.f('checkpoint_blobs_thread_id_idx'), 'checkpoint_blobs', ['thread_id'], unique=False)
    op.drop_table('team_theme_settings')
    op.drop_table('user_theme_settings')
    op.drop_table('organization_theme_settings')

    # Drop enum types
    sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitationstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='orgrole').drop(op.get_bind(), checkfirst=True)
    sa.Enum('ADMIN', 'MEMBER', 'VIEWER', name='teamrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
