"""Add conversation_message index table for search

Revision ID: 959c0f0c6e08
Revises: m2n3o4p5q6r7

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '959c0f0c6e08'
down_revision: Union[str, Sequence[str], None] = 'm2n3o4p5q6r7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pg_trgm extension for trigram similarity search
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_message_conversation_id'), 'conversation_message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_message_created_by_id'), 'conversation_message', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_conversation_message_organization_id'), 'conversation_message', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversation_message_team_id'), 'conversation_message', ['team_id'], unique=False)

    # Create GIN index for fast full-text search on message content
    op.execute("""
        CREATE INDEX idx_conversation_message_content_gin
        ON conversation_message
        USING gin (content gin_trgm_ops);
    """)

    # Create composite index for multi-tenant filtering with DESC sort on created_at
    op.create_index(
        'idx_conversation_message_team_user',
        'conversation_message',
        ['team_id', 'created_by_id', sa.text('created_at DESC')],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversation_message_team_user', table_name='conversation_message')
    op.execute("DROP INDEX IF EXISTS idx_conversation_message_content_gin;")
    op.drop_index(op.f('ix_conversation_message_team_id'), table_name='conversation_message')
    op.drop_index(op.f('ix_conversation_message_organization_id'), table_name='conversation_message')
    op.drop_index(op.f('ix_conversation_message_created_by_id'), table_name='conversation_message')
    op.drop_index(op.f('ix_conversation_message_conversation_id'), table_name='conversation_message')
    op.drop_table('conversation_message')
    # Note: Not dropping pg_trgm extension as it may be used by other tables
    # ### end Alembic commands ###
