/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsPromptsRouteImport } from './routes/settings.prompts'
import { Route as OrgSettingsRouteImport } from './routes/org/settings'
import { Route as OrgPromptsRouteImport } from './routes/org/prompts'
import { Route as OrgApiKeysRouteImport } from './routes/org/api-keys'
import { Route as OrgTeamTeamIdSettingsRouteImport } from './routes/org/team/$teamId.settings'
import { Route as OrgTeamTeamIdPromptsRouteImport } from './routes/org/team/$teamId.prompts'
import { Route as OrgTeamTeamIdApiKeysRouteImport } from './routes/org/team/$teamId.api-keys'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPromptsRoute = SettingsPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => SettingsRoute,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/org/settings',
  path: '/org/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgPromptsRoute = OrgPromptsRouteImport.update({
  id: '/org/prompts',
  path: '/org/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgApiKeysRoute = OrgApiKeysRouteImport.update({
  id: '/org/api-keys',
  path: '/org/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamTeamIdSettingsRoute = OrgTeamTeamIdSettingsRouteImport.update({
  id: '/org/team/$teamId/settings',
  path: '/org/team/$teamId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamTeamIdPromptsRoute = OrgTeamTeamIdPromptsRouteImport.update({
  id: '/org/team/$teamId/prompts',
  path: '/org/team/$teamId/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgTeamTeamIdApiKeysRoute = OrgTeamTeamIdApiKeysRouteImport.update({
  id: '/org/team/$teamId/api-keys',
  path: '/org/team/$teamId/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/org/api-keys': typeof OrgApiKeysRoute
  '/org/prompts': typeof OrgPromptsRoute
  '/org/settings': typeof OrgSettingsRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/org/team/$teamId/api-keys': typeof OrgTeamTeamIdApiKeysRoute
  '/org/team/$teamId/prompts': typeof OrgTeamTeamIdPromptsRoute
  '/org/team/$teamId/settings': typeof OrgTeamTeamIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/org/api-keys': typeof OrgApiKeysRoute
  '/org/prompts': typeof OrgPromptsRoute
  '/org/settings': typeof OrgSettingsRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/org/team/$teamId/api-keys': typeof OrgTeamTeamIdApiKeysRoute
  '/org/team/$teamId/prompts': typeof OrgTeamTeamIdPromptsRoute
  '/org/team/$teamId/settings': typeof OrgTeamTeamIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/invite': typeof InviteRoute
  '/login': typeof LoginRoute
  '/organizations': typeof OrganizationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/org/api-keys': typeof OrgApiKeysRoute
  '/org/prompts': typeof OrgPromptsRoute
  '/org/settings': typeof OrgSettingsRoute
  '/settings/prompts': typeof SettingsPromptsRoute
  '/org/team/$teamId/api-keys': typeof OrgTeamTeamIdApiKeysRoute
  '/org/team/$teamId/prompts': typeof OrgTeamTeamIdPromptsRoute
  '/org/team/$teamId/settings': typeof OrgTeamTeamIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/invite'
    | '/login'
    | '/organizations'
    | '/search'
    | '/settings'
    | '/signup'
    | '/org/api-keys'
    | '/org/prompts'
    | '/org/settings'
    | '/settings/prompts'
    | '/org/team/$teamId/api-keys'
    | '/org/team/$teamId/prompts'
    | '/org/team/$teamId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/invite'
    | '/login'
    | '/organizations'
    | '/search'
    | '/settings'
    | '/signup'
    | '/org/api-keys'
    | '/org/prompts'
    | '/org/settings'
    | '/settings/prompts'
    | '/org/team/$teamId/api-keys'
    | '/org/team/$teamId/prompts'
    | '/org/team/$teamId/settings'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/invite'
    | '/login'
    | '/organizations'
    | '/search'
    | '/settings'
    | '/signup'
    | '/org/api-keys'
    | '/org/prompts'
    | '/org/settings'
    | '/settings/prompts'
    | '/org/team/$teamId/api-keys'
    | '/org/team/$teamId/prompts'
    | '/org/team/$teamId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  InviteRoute: typeof InviteRoute
  LoginRoute: typeof LoginRoute
  OrganizationsRoute: typeof OrganizationsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  OrgApiKeysRoute: typeof OrgApiKeysRoute
  OrgPromptsRoute: typeof OrgPromptsRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  OrgTeamTeamIdApiKeysRoute: typeof OrgTeamTeamIdApiKeysRoute
  OrgTeamTeamIdPromptsRoute: typeof OrgTeamTeamIdPromptsRoute
  OrgTeamTeamIdSettingsRoute: typeof OrgTeamTeamIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/prompts': {
      id: '/settings/prompts'
      path: '/prompts'
      fullPath: '/settings/prompts'
      preLoaderRoute: typeof SettingsPromptsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/org/settings': {
      id: '/org/settings'
      path: '/org/settings'
      fullPath: '/org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/prompts': {
      id: '/org/prompts'
      path: '/org/prompts'
      fullPath: '/org/prompts'
      preLoaderRoute: typeof OrgPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/api-keys': {
      id: '/org/api-keys'
      path: '/org/api-keys'
      fullPath: '/org/api-keys'
      preLoaderRoute: typeof OrgApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/team/$teamId/settings': {
      id: '/org/team/$teamId/settings'
      path: '/org/team/$teamId/settings'
      fullPath: '/org/team/$teamId/settings'
      preLoaderRoute: typeof OrgTeamTeamIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/team/$teamId/prompts': {
      id: '/org/team/$teamId/prompts'
      path: '/org/team/$teamId/prompts'
      fullPath: '/org/team/$teamId/prompts'
      preLoaderRoute: typeof OrgTeamTeamIdPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/team/$teamId/api-keys': {
      id: '/org/team/$teamId/api-keys'
      path: '/org/team/$teamId/api-keys'
      fullPath: '/org/team/$teamId/api-keys'
      preLoaderRoute: typeof OrgTeamTeamIdApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsPromptsRoute: typeof SettingsPromptsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsPromptsRoute: SettingsPromptsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  InviteRoute: InviteRoute,
  LoginRoute: LoginRoute,
  OrganizationsRoute: OrganizationsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  OrgApiKeysRoute: OrgApiKeysRoute,
  OrgPromptsRoute: OrgPromptsRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  OrgTeamTeamIdApiKeysRoute: OrgTeamTeamIdApiKeysRoute,
  OrgTeamTeamIdPromptsRoute: OrgTeamTeamIdPromptsRoute,
  OrgTeamTeamIdSettingsRoute: OrgTeamTeamIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
